name: digest_reads
description: Digest long-read concatemers into monomers at restriction sites.
keywords:
  - digest
  - pore-c
  - longc
  - restriction
  - monomers
tools:
  - digest_reads:
      description: Python script to split concatemers at restriction sites
input:
  - meta:
      type: map
      description: Sample metadata
  - tabular:
      type: file
      description: Tabular format (name, seq, qual) from seqkit fx2tab
  - cutter:
      type: string
      description: Restriction enzyme name (e.g. NlaIII)
output:
  digested_tabular:
    - meta:
        type: map
    - "*.tsv.gz":
        type: file
        description: Digested monomer sequences in tabular format
