lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-tollongc_logo_light.png
    - docs/images/nf-core-tollongc_logo_light.png
    - docs/images/nf-core-tollongc_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-tollongc_logo_light.png
    - docs/images/nf-core-tollongc_logo_light.png
    - docs/images/nf-core-tollongc_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: yumisims
  description: The Long-C pipeline processes long-read chromatin conformation capture
    sequencing data to detect multi-fragment DNA contacts within the genome. These
    contacts reflect the three-dimensional organization of chromatin. The pipeline
    converts raw sequencing reads into pairwise genomic interactions and generates
    contact matrices suitable for visualization and downstream analysis.
  force: false
  is_nfcore: false
  name: tollongc
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 1.0.0dev
